apiVersion: apps/v1
kind: deployment
metadata: 
  name: nginxapp
spec:
  selector: 
    matchLabels: 
      app: nginxapp
  replicas: 4
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginxapp
        image: nginx
        ports:
        - containerPort: 8888
